services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  penguins-db:
    image: mysql:8.0
    container_name: penguins-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: penguins_db
      MYSQL_USER: penguins_user
      MYSQL_PASSWORD: penguins_pass
    ports:
      - "3306:3306"
    volumes:
      - penguins_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  airflow-init:
    image: airflow-pinguinos:local
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey"
      AIRFLOW__CORE__FERNET_KEY: "0123456789abcdef0123456789abcdef"
      MODELS_DIR: /opt/airflow/models
    volumes:
      - models_dir:/opt/airflow/models
    # Usamos la forma de lista: ["bash", "-c", "comando..."]
    entrypoint:
      - bash
      - -c
      - |
        airflow db migrate && \
        airflow users create \
          --username admin \
          --password admin \
          --firstname Jacobo \
          --lastname Admin \
          --role Admin \
          --email admin@example.com
    restart: "no"

  airflow-webserver:
    build: .
    image: airflow-pinguinos:local
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey"
      AIRFLOW__CORE__FERNET_KEY: "0123456789abcdef0123456789abcdef"
      MODELS_DIR: /opt/airflow/models
    ports:
      - "8080:8080"
    command: webserver
    restart: always
    volumes:
      - models_dir:/opt/airflow/models

  airflow-scheduler:
    image: airflow-pinguinos:local
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey"
      AIRFLOW__CORE__FERNET_KEY: "0123456789abcdef0123456789abcdef"
      MODELS_DIR: /opt/airflow/models
    command: scheduler
    restart: always
    volumes:
      - models_dir:/opt/airflow/models

  penguins-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: penguins-api
    depends_on:
      penguins-db:
        condition: service_healthy
    environment:
      MODELS_DIR: /opt/airflow/models
      MYSQL_HOST: penguins-db
      MYSQL_PORT: "3306"
      MYSQL_DB: penguins_db
      MYSQL_USER: penguins_user
      MYSQL_PASSWORD: penguins_pass
    volumes:
      - models_dir:/opt/airflow/models
    command: >
      python -m uvicorn airflow_pinguinos.api:app
      --host 0.0.0.0
      --port 8000
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  airflow_logs:
  penguins_db_data:
  models_dir: